spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/srms_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.skye: debug
